# -*- coding: utf-8 -*-
"""Crystal Growth Aid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IvTl0eIMHR_RZ-XzVywrMTMdbSyX06VX
"""

print ("Welcome to Crystal Growth Aid, This tool gives you some intitial idea of your crystallization")
print ("**************************************************************************************************************")
print ()

while True:
    answer = input("Are you redy? type 'yes' or 'no'   ").strip().lower()
    if answer == "yes":
        print()
        print("Great... Let's start")
        break
    elif answer == "no":
        print()
        print("Come on... Let's try")
        break
    else:
        print()
        print("please only type 'yes' or 'no' ")

print("*****************************************************************************************************************")
print()
print("Now you should define type of your compound: Organic, Inorganic, Polymer, Protein  ")
print()

while True:
        chemical_type = input("what is the type of your compound of study?  ").strip().lower()
        if chemical_type in ("organic" , "inorganic"):
            print()
            print("very good, there are several options available for you ")
            print("You need to choose one of the following methods: ")
            print("1. Slow evaporation")
            print("2. Slow cooling")
            print("3. Vapor diffusion")
            print("4. liquid diffusion or layering")
            print("5. Solvothermal")
            print()

            while True:
                Crystallization_method = input("Which one of the methods do you choose?").strip().lower()

                if Crystallization_method in ("slow evaporation" , "1"):
                    print()
                    print("""
                    Slow Evaporation is the most common and easiest technique
                    that we use for the crystallization of small molecules.
                    It is usually the first trial for a crystallization.
                    We simply dissolve our sample in a solvent and let our solvent evaporate slowly.
                    This method does not give the best quality of crystals in general.
                    The evaporation rate can be slowed down by controlling the surface area of our vessel,
                    by covering it using parafilm or a rubber septum, or by cooling the solution.
                    This method can be done inside an inert atmosphere as well.""")
                    print()
                    solvent_type = input("what is the solvent of your compound?").strip().lower()
                    print()
                    print("Great!!! Disolve a littile amount of your compound in about 1.5 ml of", solvent_type ,"then let it to evaporate slowly"
                    "If the solvent evaporates quickly, seal the lid of the vial with parafilm, then create some holes using a needle. " )
                    print()
                    break

                elif Crystallization_method in ("slow cooling" , "2"):
                    print()
                    print("""This method is a standard way to recrystallize our small molecules.
                    However, it can be employed as a method for direct crystallization.
                    To this end, usually after heating the solution of our compound,
                    we avoid fast cooling and try to decrease the temperature in a controlled
                    and slow way. For example, we can place the vial of our solution into another
                    container like a Styrofoam box, a jar filled with cotton, an oil bath,
                    or control the temperature using an oven.""")
                    print()
                    solvent_type = input("What is the solvent of your compound?").strip().lower()
                    print()
                    print("Great!!! Then dissolve a little amount of your compound in about 1.5 ml of", solvent_type ,"and let it to cool down slowly" )
                    print()
                    break

                elif Crystallization_method in ("vapor diffusion" , "3"):
                    print()
                    print("""This approach is one of the best choices for small molecule crystallization,
                    especially if we do not have much of our compound.
                    The vapor diffusion method is done by dissolving your compound in a small vial
                    and then placing that vial inside a larger vial that contains a small volume of
                    antisolvent for our compound. The vapors of the antisolvent diffuse to the solution
                    slowly and cause the crystallization of our compounds. It should be noted that the
                    system is closed, and it can be placed in a fridge or at room temperature.""")
                    print()
                    solvent_type = input("What is the solvent of your compound?").strip().lower()
                    print()
                    antisolvent_type = input ("What is the antisolvent of your compound?").strip().lower()
                    print()
                    print("Great!!! First dissolve a little amount of your compound in about 1.5 ml of", solvent_type ,
                    "then, put the vial of your compound in a bigger vial that is filled with 1.5ml of" , antisolvent_type , "and close the system" )
                    print()
                    break

                elif Crystallization_method in ("layering" , "liquid diffusion" , "4"):
                    print("""The layering method or liquid-liquid diffusion,
                    relies on the slow mixing of two miscible or partially miscible liquids:
                    a solvent and an antisolvent. You dissolve your compound in a small amount of a suitable solvent.
                    You choose a second liquid that mixes with the solvent, but in which your compound will not dissolve.
                    The lower-density liquid is carefully layered on top of the higher-density liquid in a narrow, tall vial, like NMR tube.
                    Over time, the two liquids slowly diffuse into each other across the boundary layer.
                    As the antisolvent gradually enters the solvent layer, the solubility of your compound drops slowly enough to promote orderly
                    crystal growth rather than rapid precipitation. """)
                    print()
                    solvent_type = input("What is the solvent of your compound?").strip().lower()
                    print()
                    antisolvent_type = input ("What is the antisolvent of your compound?").strip().lower()
                    print()
                    print(f"""Great!!! First dissolve a little amount of your compound in about 1 ml of {solvent_type}
                        then, pour it to a NMR tube. After that slowly add the {antisolvent_type} and close
                        the system. Be carefull about the density of the solvent and antisolvnt""")
                    print()
                    break

                elif Crystallization_method in ("solvothermal" , "5"):
                    print("""Hydrothermal and solvothermal synthesis are methods used to create crystalline materials under high temperature and
                    pressure in a closed system (autoclave). Hydrothermal synthesis uses water as the solvent, while solvothermal synthesis uses
                    other solvents such as alcohols or organic liquids. These techniques allow controlled growth of high-quality crystals by adjusting
                    factors like temperature, pressure, reaction time, and reactant concentration. Hydrothermal methods are commonly used for
                    materials like oxides, silicates, and zeolites, whereas solvothermal methods are useful for materials such as metal-organic
                    frameworks (MOFs) and nanomaterials.The synthesis conditions influence crystal size, shape, structure, and properties
                    by controlling nucleation and crystal growth. """)
                    print()
                    solvent_type = input("What is the solvent of your compound?").strip().lower()
                    print()
                    print("First, dissolve a small amount of your compound in about 5 mL of", solvent_type , "then, pour the solution of your compound"
                            "into a Teflon vial in an autoclave. Transfer the autoclave to an oven and program the oven for crystallization. " )
                    print()
                    break

                else:
                    print()
                    print("Invalid crystallization method selected.")
                    print()
            break

        elif chemical_type == "polymer" or chemical_type == "protein":
            print()
            print("This programm is not usefull for you yet")
            break

        else:
            print()
            print("please choose one of these: Organic, Inorganic, Polymer, Protein")
            print()

print("********************************************************************************************************")
print("Thank you very much for using Crystal Growth Aid")
print("********************************************************************************************************")

